### ISSUE TITLE
ModuleNotFoundError: No module named 'limesurveyrc2api.limesurvey'

### ISSUE THREAD

**Issue by AmauryVanEspen** [lindsay-stevens/limesurveyrc2api#14]
Hello

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-a3d447d8af23>](https://localhost:8080/#) in <module>
----> 1 from limesurveyrc2api.limesurvey import LimeSurvey
      2 
      3 url = "http://aredil.freeboxos.fr:8036/index.php/admin/remotecontrol"
      4 username = "admin"
      5 password = "password"

ModuleNotFoundError: No module named 'limesurveyrc2api.limesurvey'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

I've installed the whole module
!pip install limesurveyrc2api

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting limesurveyrc2api
  Downloading limesurveyrc2api-1.0.0-py3-none-any.whl (7.6 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from limesurveyrc2api) (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->limesurveyrc2api) (2022.12.7)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->limesurveyrc2api) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->limesurveyrc2api) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->limesurveyrc2api) (1.26.14)
Installing collected packages: limesurveyrc2api
Successfully installed limesurveyrc2api-1.0.0

unfortunately, it doesn't help

could you please provide insight ?

Thank you

**Comment by lindsay-stevens** [comment]
Addressed in #15
