### ISSUE TITLE
Why pip install another version of the api?

### ISSUE THREAD

**Issue by isccarrasco** [lindsay-stevens/limesurveyrc2api#7]
Hi folks.
I've an issue installing the cliente.

When I ran `pip install limesurveyrc2api` to use it in my project, I received another versión where i have to use or instantiate from `LimeSurveyRemoteControl2API` instead `LimeSurvey`.

Are you planing to send the upgrade to the pypi repository?

Thanks.

**Comment by vectorson** [comment]
Until the package on PyPI gets updated, you can install the latest version using:
`pip install git+https://github.com/lindsay-stevens/limesurveyrc2api#egg=limesurveyrc2api`

**Comment by isccarrasco** [comment]
Thanks a lot @vectorson i'm going to try installing with this code.
